"""Initial migration

Revision ID: 588328c06d2b
Revises: 
Create Date: 2026-03-24 15:17:50.356648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588328c06d2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('battery_type', sa.String(), nullable=True),
    sa.Column('battery_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_battery_type'), 'devices', ['battery_type'], unique=False)
    op.create_index(op.f('ix_devices_device_name'), 'devices', ['device_name'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_battery_type'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
